[build]
  publish = "dist"
[[redirects]]
  from = "/signIn"
  to = "/"
  status = 200
[[redirects]]
  from = "/signUp"
  to = "/"
  status = 200
[[redirects]]
  from = "/error404"
  to = "/"
  status = 200
[[redirects]]
  from = "/error500"
  to = "/"
  status = 200
[[redirects]]
  from = "/profile"
  to = "/"
  status = 200
[[redirects]]
  from = "/profile/password"
  to = "/"
  status = 200
[[redirects]]
  from = "/profile/change"
  to = "/"
  status = 200
